### ISSUE TITLE
No full register view under Raspbarry OS

### ISSUE THREAD

**Issue by kosmosgit** [Milo-D/libvmcu-Virtual-MCU-Library#42]
No full register view under Raspbarry OS

Despite the very small font, not all registers are displayed in the register window.

This is probably due to the excessive spacing or fixed character positions. 01 instead of 1 would also be better so that it always sits one below the other and a smaller distance of 3-4 characters should also be enough so that you can get more informations.

Suggestion:
```
R01: xxx   ...
R02: xxx   R09: xxx
R03: xxx   R10: xxx
R04: xxx   R11: xxx
```
Otherwise I would like to be able to switch the register view between hex and dec by command, e.g. with rd or rh

![MDX_Register](https://user-images.githubusercontent.com/60920023/101447167-f5c70980-3924-11eb-8528-53c7b94ce0b3.png)

**Comment by Milo-D** [comment]
`Despite the very small font`

You can still resize the view. Issue #41 will only occur when your font is too big so that some components can not be displayed properly.

`not all registers are displayed in the register window`

You can turn pages with 'rn' (register next) and 'rp' (register previous). See wiki for more information.

Also I noticed that you are trying to simulate the elpm instruction. ELPM is currently implemented as a 'nop' instruction because the ATmega328 has no RAMP registers. What type of microcontroller are you trying to simulate ?

Otherwise I am working on a more responsive CLI with dynamic character positioning but it could take a while to finish.

**Comment by Milo-D** [comment]
I am currently moving the debugger to another repository, so I will close this issue.
